# Generated by Django 6.1 on 2026-08-14 07:09

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0002_rename_databaseconection_databaseconnection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragdocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
