# Generated by Django 6.1 on 2026-08-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0003_ragdocument_embedding'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ragdocument',
            constraint=models.UniqueConstraint(fields=('database', 'document_type', 'source_table'), name='unique_rag_document_source'),
        ),
    ]
