# Generated by Django 6.1 on 2026-08-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0004_ragdocument_unique_rag_document_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
